### ISSUE TITLE
SSL Record Too Long

### ISSUE THREAD

**Issue by PenguinzTech** [lxc-webpanel/LXC-Web-Panel#105]
Receive the following error from site when connecting via HTTPS (firefox in safe mode)
`
Secure Connection Failed

An error occurred during a connection to 192.168.67.112:5000. SSL received a record that exceeded the maximum permissible length. (Error code: ssl_error_rx_record_too_long)`

**Comment by ElieDeloumeau** [comment]
SSL is not supported in LWP 0.2
