### ISSUE TITLE
Creating CentOS requires yum

### ISSUE THREAD

**Issue by perpetual-hydrofoil** [lxc-webpanel/LXC-Web-Panel#107]
Just a minor issue. Attempting to create a centos lxc container causes the web ux to crash:

`The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`

Running manually shows that yum is missing:

```
Host CPE ID from /etc/os-release: 
'yum' command is missing
lxc-create: lxccontainer.c: create_run_template: 1297 container creation template for CentOS failed

```

sudo apt-get install yum fixes it.

**Comment by ElieDeloumeau** [comment]
Thanks for reporting this issue.
I will fix it in https://github.com/lxc-webpanel/lxc-rest with a warning message or something else.
