### ISSUE TITLE
Missing fabric file?

### ISSUE THREAD

**Issue by jondkelley** [lxc-webpanel/LXC-Web-Panel#114]
Has the project stopped using fabric?

If there is a workaround I can make a pull request for the documentation on CentOS. Thanks.

### Expected Behavior

Just following initial steps http://claudyus.github.io/LXC-Web-Panel/ see also: "Installation on rpm system"

      git clone  git clone https://github.com/lxc-webpanel/LXC-Web-Panel.git
      cd LXC-Web-Panel
      fab build_assets         # build assets using python-fabric
      <Expect the installer to prepare assets>

### Actual Behavior

      # git clone  git clone https://github.com/lxc-webpanel/LXC-Web-Panel.git
      # cd LXC-Web-Panel
      # fab build_assets 
      Fatal error: Couldn't find any fabfiles!
      Remember that -f can be used to specify fabfile path, and use -h for help.
      Aborting.

### Steps to Reproduce the Problem

  1. See above (actual behavior)

### Cause of Problem

We need a fab.py. I don't see "import fabric" anywhere in LXC-WEB code...

### Specifications

  - LXC Version:
lxc-templates-1.0.11-1.el7.x86_64
lxc-libs-1.0.11-1.el7.x86_64
lxc-1.0.11-1.el7.x86_64
lxc-extra-1.0.11-1.el7.x86_64
lxc-devel-1.0.11-1.el7.x86_64
python34-lxc-1.0.11-1.el7.x86_64
lua-lxc-1.0.11-1.el7.x86_64
  - LWP Version:
  - OS Name:
CentOS Linux
  - OS Version:
release 7.4.1708 (Core)

**Comment by ElieDeloumeau** [comment]
Hi, you are on the wrong repo.
