### ISSUE TITLE
How to access running container (i.e. get a terminal connected)

### ISSUE THREAD

**Issue by sihorton** [lxc-webpanel/LXC-Web-Panel#39]
I have installed lxc-webpanel on a fresh ubuntu 12.04 and I can login to the control panel with admin/admin. I can create containers and run and stop them ok. How do I then customise / configure the containers that are created? I am expecting to be able to connect a terminal to a container or ssh into the machine.

If I create a ubuntu container for example I can then ssh to the ip address of the container but it asks for username / password and I cannot find any documentation that says what this is set to. Likewise I can create containers of the other types but I cannot find documentation on what these images contain or how they are configured so am unable to get any further.

**Comment by viogq** [comment]
>  login to the control panel with admin/admin 

that's all people want to know. passwords are always kept kinda hidden, so no one can use the software right away.
