### ISSUE TITLE
500 Internal Server Error (Bug)

### ISSUE THREAD

**Issue by abessifi** [lxc-webpanel/LXC-Web-Panel#41]
Am using LWP on Debian. Basically all it works fine, but when I clicked on "Networking" link (sidebar nav) it says :

> Internal Server Error
> The server encountered an internal error and was unable to complete your request. >Either the server is overloaded or there is an error in the application.

Otherwise, in debugging mode I had these exceptions :

> 127.0.0.1 - - [10/Oct/2013 11:48:04] "GET /settings/lxc-net HTTP/1.1" 500 -
> Traceback (most recent call last):
>  File "/home/ahmed/Projects/LXC-Web-Panel/lwp.py", line 285, in lxc_net
>    return render_template('lxc-net.html', containers=lxc.ls(), >cfg=lwp.get_net_settings(), running=lxc.running())
>  File "/home/ahmed/Projects/LXC-Web-Panel/lwp/**init**.py", line 238, in >get_net_settings
>    cfg['use'] = config.get('DEFAULT', 'USE_LXC_BRIDGE').strip('"')
> File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
>    raise NoOptionError(option, section)
> NoOptionError: No option 'use_lxc_bridge' in section: 'DEFAULT'

Here I think where the problem comes from (some net settings don't figure out in /etc/default/lxc) and I'll try to fix that.

**Comment by lgwapnitsky** [comment]
I have the latest version from github, and I'm still receiving the error when trying to go to network settings.  Advice?

Thank you

**Comment by SchefferKD** [comment]
I got this Error too, but I found out that a solution:
This is the original /etc/default/lxc-net, and all Variables are disabled by '#':

cat /etc/default/lxc-net
#USE_LXC_BRIDGE="true"
#LXC_BRIDGE="lxcbr0"
#LXC_ADDR="10.0.3.1"
#LXC_NETMASK="255.255.255.0"
#LXC_NETWORK="10.0.3.0/24"
#LXC_DHCP_RANGE="10.0.3.2,10.0.3.254"
#LXC_DHCP_MAX="253"
#LXC_DHCP_CONFILE=""
#LXC_DOMAIN=""

I've set USE_LXC_BRIDGE="false" and removed all '#', then it is working fine.
