### ISSUE TITLE
Files in /var/lib/lxc/* listed as containers even if they're just logfiles/temp-files

### ISSUE THREAD

**Issue by rnts08** [lxc-webpanel/LXC-Web-Panel#50]
How to reproduce; touch /var/lib/lxc/testfile, and the UI displays 'testfile' as a container. 

In lxclite/**init**.py:
Replace: 
ct_list = os.listdir('/var/lib/lxc/')
- with -

ct_dir = '/var/lib/lxc'
ct_list = [d for d in os.listdir(ct_dir) if os.path.isdir(os.path.join(ct_dir, d))]

Fixed.

**Comment by ElieDeloumeau** [comment]
No more directory listing in https://github.com/lxc-webpanel/LXC-Web-Panel/tree/develop
