### ISSUE TITLE
lost+found

### ISSUE THREAD

**Issue by crpb** [lxc-webpanel/LXC-Web-Panel#76]
Hi,

just tried out the Webpanel and after i created an extra FS for /var/lib/lxc it wouldn't work anymore.

So far the function "ls()" in lxclite/**init**.py lists the ext\* lost+found as an container.

So my quick and dirty fix was this..

``` python
157a158,159
>     ct_list.remove("lost+found")
```

**Comment by ElieDeloumeau** [comment]
No more directory listing in https://github.com/lxc-webpanel/LXC-Web-Panel/tree/develop
