### ISSUE TITLE
Python error when creating a container

### ISSUE THREAD

**Issue by Justinzobel** [lxc-webpanel/LXC-Web-Panel#90]
TypeError
TypeError: not all arguments converted during string formatting

Traceback (most recent call last)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1701, in **call**
return self.wsgi_app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1689, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1687, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1360, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1358, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1344, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/srv/lwp/lwp.py", line 692, in create_container
flash(u'Error!' % name, 'error')
TypeError: not all arguments converted during string formatting
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by Justinzobel** [comment]
Noob issue, closing.

**Comment by yunier-rojas** [comment]
Does any one know how to fix this issue??

**Comment by Justinzobel** [comment]
@yunier-rojas apparently not as it's been open nearly a year and no comment from the dev.

**Comment by marioabajo** [comment]
In my case the error was caused because of lack of internet connection, i supposed that the commands that tried to download from the mirrors the packages to create the container failed. Restoring internet connection solved the issue.

**Comment by Justinzobel** [comment]
Nearly 2 years, no answer from devs :(

**Comment by ElieDeloumeau** [comment]
@Justinzobel but an answer from @marioabajo
