### ISSUE TITLE
Is there any user permission system

### ISSUE THREAD

**Issue by aodzip** [lxc-webpanel/LXC-Web-Panel#96]
A normal user can control all containers , it is seems not safe

**Comment by googley** [comment]
in the next version you can set permissions on each containers, modules (users management, network, containers, etc...) and rights per modules (ex: add/remove/edit users).

**Comment by aodzip** [comment]
I am looking for it!
Thanks for your great work.

**Comment by ElieDeloumeau** [comment]
Work in progress https://github.com/lxc-webpanel/LXC-Web-Panel/tree/develop
